import type { APIRoute } from 'astro';
import { CURRENCIES, toStripeAmount } from '@data/donation.mjs';
import { SITE_URL } from '@data/site.mjs';

/**
 * POST /api/create-donation — creates a Stripe Checkout Session for a one-time
 * or monthly donation of an arbitrary amount/currency, and returns its hosted
 * `checkout_url` for the browser to redirect to. This is the one server-side
 * piece of the donate flow: it holds the Stripe SECRET key, which must never
 * reach the client. Faithful replacement for the live WordPress AJAX action
 * `app_create_donation_payment`.
 *
 * Runtime: on-demand (NOT prerendered) — runs as an on-demand Cloudflare Worker
 * invocation via @astrojs/cloudflare (v14, Workers-only; NOT a Pages Function).
 * Uses only Web-standard fetch/Request/Response +
 * form-encoded Stripe REST (no Stripe SDK), so the logic is host-portable: to
 * move off Cloudflare, swap the adapter and the env access below is already
 * host-neutral.
 *
 * On the AWS Amplify deployment this route does NOT run — its Lambda twin
 * (`aws/create-donation/index.mjs`) serves the same path behind an Amplify
 * rewrite. THIS file is the contract source: keep the twin's request/response
 * behavior (and `safeOrigin`) in step with it.
 *
 * Dormant until STRIPE_SECRET_KEY is set (Cloudflare secret in prod; a local
 * .dev.vars line for `astro dev`). Without it the endpoint returns 503 and the
 * modal surfaces a friendly error — nothing else in the build depends on it.
 */
export const prerender = false;

const STRIPE_API = 'https://api.stripe.com/v1/checkout/sessions';
const CURRENCY_SET = new Set(CURRENCIES.map((c) => c.toUpperCase()));

/**
 * The ONE host-specific seam — runtime env reads. On Cloudflare (dev + prod)
 * the runtime binding is read from the `cloudflare:workers` virtual module; on
 * Node/Vercel/Netlify it comes from `process.env`. The dynamic import is
 * guarded so the file stays host-neutral at the source level — moving hosts
 * touches only this helper.
 */
async function readRuntimeEnv(name: string): Promise<string | undefined> {
  try {
    // On workerd this module IS the environment, so its `env` is authoritative:
    // return whatever it holds, INCLUDING undefined. Do not fall through — Vite
    // inlines the fallback below as a string literal at build time, so a
    // fall-through would (a) let a stale build-time value shadow the real
    // "secret not provisioned yet" state (503) and (b) bake a local .dev.vars
    // value into the production bundle. Verified 2026-07-27: a placeholder in
    // .dev.vars compiled to `return "PASTE_TEST_SECRET_KEY_HERE"` and was
    // deployed, making the dormant endpoint 502 against Stripe instead of 503.
    const mod: any = await import('cloudflare:workers');
    return mod?.env?.[name];
  } catch {
    /* not running on a workerd runtime — fall through */
  }
  // Deliberately NOT `import.meta.env[…]`: Vite resolves that at BUILD time and
  // inlines the value as a string literal, so any local .dev.vars key would be
  // embedded in the shipped bundle (dead code here, but still a secret sitting
  // in a build artifact). `process.env` is read at RUNTIME and covers the same
  // Node-ish hosts (Vercel/Netlify/node adapter).
  return typeof process !== 'undefined' ? process.env?.[name] : undefined;
}

const getStripeKey = () => readRuntimeEnv('STRIPE_SECRET_KEY');

/**
 * Post-payment return origin: the browser's Origin header if it's one of ours —
 * the canonical site, or an https host on/under APP_DOMAIN (the deploy's
 * preview domain, e.g. the Amplify app domain) — else SITE_URL. Validated,
 * never trusted: Origin is attacker-supplied and becomes the redirect target
 * Stripe sends the donor (and the session_id) to. Mirrors the Lambda twin's
 * `safeOrigin` — keep the two in step.
 */
function safeOrigin(request: Request, appDomain: string | undefined): string {
  const origin = request.headers.get('origin') || '';
  if (origin === SITE_URL) return origin;
  if (appDomain) {
    try {
      const u = new URL(origin);
      if (u.protocol === 'https:' && (u.host === appDomain || u.host.endsWith('.' + appDomain)))
        return origin;
    } catch {
      /* malformed Origin — fall through */
    }
  }
  return SITE_URL;
}

/**
 * JSON response helper — also the ONLY place this route's security headers can
 * be set. `public/_headers` covers static-asset responses only; Cloudflare does
 * not apply it to responses generated by the Worker, and this is the one route
 * that is. So the headers here are deliberately duplicated from that file
 * rather than inherited — keep the two in step (see the note in `_headers`).
 *
 * `no-store` matters on its own account: every response is per-request (a
 * checkout URL, or a validation error) and none of it may sit in a shared cache.
 */
const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), {
    status,
    headers: {
      'content-type': 'application/json',
      'cache-control': 'no-store',
      'x-content-type-options': 'nosniff',
      'referrer-policy': 'strict-origin-when-cross-origin',
    },
  });

export const POST: APIRoute = async ({ request }) => {
  const secretKey = await getStripeKey();
  if (!secretKey) {
    // Not configured yet — the build ships this way until the secret is added.
    return json({ message: 'Donations are not available right now. Please try again later.' }, 503);
  }

  let body: { amount?: unknown; is_monthly?: unknown; currency?: unknown };
  try {
    body = await request.json();
  } catch {
    return json({ message: 'Invalid request.' }, 400);
  }

  const amount = Number(body.amount);
  const isMonthly = body.is_monthly === true || body.is_monthly === 'true';
  const currency = String(body.currency || 'USD').toUpperCase();

  if (!Number.isFinite(amount) || amount < 1) {
    return json({ message: 'Please select or enter a valid donation amount.' }, 400);
  }
  if (!CURRENCY_SET.has(currency)) {
    return json({ message: 'Unsupported currency.' }, 400);
  }

  const unitAmount = toStripeAmount(amount, currency);

  // Build the Checkout Session as form-encoded params (Stripe's REST contract).
  const params = new URLSearchParams();
  params.set('mode', isMonthly ? 'subscription' : 'payment');
  params.set('line_items[0][quantity]', '1');
  params.set('line_items[0][price_data][currency]', currency.toLowerCase());
  params.set(
    'line_items[0][price_data][product_data][name]',
    isMonthly ? 'OpenMined Monthly Donation' : 'OpenMined Donation',
  );
  params.set('line_items[0][price_data][unit_amount]', String(unitAmount));
  if (isMonthly) {
    params.set('line_items[0][price_data][recurring][interval]', 'month');
  } else {
    // Shows a "Donate" button + donation framing on Stripe's hosted page.
    params.set('submit_type', 'donate');
  }
  // Validated origin (see safeOrigin): staging/preview checkouts round-trip to
  // the host they started on, anything untrusted falls back to the canonical
  // site — never a raw Host/Origin value.
  const origin = safeOrigin(request, await readRuntimeEnv('APP_DOMAIN'));
  params.set('success_url', `${origin}/donate/thank-you/?session_id={CHECKOUT_SESSION_ID}`);
  params.set('cancel_url', `${origin}/?donate=cancelled`);
  params.set('billing_address_collection', 'auto');

  const res = await fetch(STRIPE_API, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${secretKey}`,
      'content-type': 'application/x-www-form-urlencoded',
    },
    body: params,
  });

  const data: any = await res.json();
  if (!res.ok || !data?.url) {
    const message = data?.error?.message || 'Could not start checkout. Please try again.';
    return json({ message }, 502);
  }

  return json({ checkout_url: data.url });
};
